name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gleam-version: ["1.14.0", "1.17.0"]

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28.0"
          gleam-version: ${{ matrix.gleam-version }}

      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"

      - if: matrix.gleam-version == '1.17.0'
        run: gleam format --check

      - run: gleam test --target erlang
      - run: gleam test --target javascript
