name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          gleam-version: "1.8.0"

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: gleam format --check

      - run: gleam test --target erlang
      - run: gleam test --target javascript
